services:
  app:
    build: .
    container_name: asset_prod_app
    restart: always

    ports:
      - "8003:80"

    volumes:
      - .:/var/www/html

    networks:
      - shared

networks:
  shared:
    external: true

